name: viktoriaflutter
description: A new Flutter project.

version: 2.0.3+31

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.8
  shared_preferences: ^0.5.3+4
  crypto: ^2.1.3
  flutter_svg: ^0.14.2
  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.0.1+1
  url_launcher: ^5.1.6
  material_design_icons_flutter: ^3.2.4495
  add_2_calendar: ^1.3.0
  device_info: ^0.4.0+3
  sliding_up_panel: ^0.3.6
  encrypt: ^3.3.1
  nextcloud: ^1.0.8
  open_file: ^2.0.3
  path_provider: ^1.3.1
  timeago: ^2.0.22
  file_picker: ^1.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/logo_white.svg
    - pubspec.yaml