name: viktoriaflutter
description: A new Flutter project.

version: 1.0.17+18

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  crypto: ^2.0.6
  flutter_svg: ^0.12.4
  firebase_core: ^0.3.4
  firebase_messaging: ^4.0.0+2
  url_launcher: ^5.0.2
  fluttertoast: ^3.0.3
  material_design_icons_flutter: ^3.2.3595
  flutter_mobile_vision: ^0.1.3
  add_2_calendar: ^1.2.2
  device_id: ^0.1.3
  device_info: ^0.4.0+1
  image_picker: ^0.4.12 # Don't update!
  firebase_ml_vision: ^0.7.0
  image: ^2.0.7
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  flutter_reorderable_list: ^0.1.3
  speech_recognition: ^0.3.0+1
  permission: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/logo_white.svg
    - assets/images/ginkgobewegt.gif
    - pubspec.yaml
