name: viktoriaflutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  shared_preferences: ^0.4.3
  crypto: ^2.0.6
  flutter_svg: ^0.7.0+1
  onesignal: ^1.0.3
  url_launcher: ^4.0.3
  fluttertoast: ^2.2.3
  material_design_icons_flutter: ^3.2.3595
  flutter_mobile_vision: ^0.1.3
  add_2_calendar: ^1.2.2
  device_id: ^0.1.3 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
  - family: Ubuntu
    fonts:
    - asset: assets/fonts/Ubuntu-R.ttf
  uses-material-design: true
  assets:
  - assets/images/logo.svg
  - assets/images/logo_white.svg
