name: viktoriaflutter
description: A new Flutter project.

version: 1.0.25+26

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  crypto: ^2.1.3
  flutter_svg: ^0.14.2
  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.0.1+1
  url_launcher: ^5.1.6
  material_design_icons_flutter: ^3.2.4495
  add_2_calendar: ^1.3.0
  device_id: ^0.2.0
  device_info: ^0.4.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-R.ttf
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/logo_white.svg
    - pubspec.yaml